Global:
  debug: false
  use_gpu: true
  epoch_num: 500
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/papyr_rec
  learning_rate: 0.0005
  save_epoch_step: 10
  eval_batch_step: [0, 200]
  cal_metric_during_train: true
  pretrained_model: ./output/papyr_rec/iter_epoch_100 # Default model: ./pretrained_models/PP-OCRv5_server_rec_pretrained 
  checkpoints: 
  save_inference_dir:
  use_visualdl: false
  infer_img:
  character_dict_path: ./data/vn_dictionary.txt
  character_type: ch
  use_space_char: true
  distributed: false
  max_text_length: 64
  save_res_path: ./output/rec/predicts_rec.txt

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.0005
    warmup_epoch: 5
  regularizer:
    name: L2
    factor: 3.0e-05

Architecture:
  model_type: rec
  algorithm: SVTR_LCNet
  Transform:
  Backbone:
    name: PPLCNetV3
    scale: 1.0
  Neck:
    name: SequenceEncoder
    encoder_type: svtr
    dims: 120
    depth: 2
    hidden_dims: 120
    use_guide: True
  Head:
    name: CTCHead
    fc_decay: 0.00001

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc
  ignore_space: true

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./
    ext_op_transform_idx: 1
    label_file_list: ["./vi_rec_train_list.txt"]
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - RecConAug:
          prob: 0.5
          ext_data_num: 2
          image_shape: [48, 640, 3]
          max_text_length: 64
      - CTCLabelEncode:
      - RecResizeImg:
          image_shape: [3, 48, 640]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length']
  loader:
    shuffle: true
    batch_size_per_card: 64
    drop_last: true
    num_workers: 4 # Kept at 4 for better IPS on Windows

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./
    label_file_list: ["./vi_rec_val_list.txt"]
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - CTCLabelEncode:
      - RecResizeImg:
          image_shape: [3, 48, 640]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length']
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 64
    num_workers: 1